modLoader="javafml"
loaderVersion="[41,)"
license="MIT License https://github.com/McJtyMods/TheOneProbe/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/TheOneProbe/issues"
displayURL="http://github.com/McJtyMods/TheOneProbe/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="theoneprobe"
version="${file.jarVersion}"
displayName="The One Probe"
#updateJSONURL="http://myurl.me/" #optional
description='''
The One Probe lets you examine the block that you are looking at. Having a
probe in your hand lets you examine it better but you can also make this
probe required if you so desire.
'''
[[dependencies.theoneprobe]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.99,)"
    ordering="NONE"
    side="BOTH"
